package:
  name: {{ cookiecutter.project_slug }}
  version: 0.1.0

source:
  git_url: ../

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

  # Specify additional env vars pass through
  script_env:
    # Used to specify which Python version to build against
    - PYTHON_BUILD_VERSION

requirements:
  build:
    # We default to Python 3.6 if no environment variable is set
    - python {{ environ.get("PYTHON_BUILD_VERSION", "3.6") }}*
    - setuptools

  run:
    - python {{PY_VER}}*
    - vs2015_runtime  [win]

test:
  # Test that we can import the package
  imports:
    - {{ cookiecutter.project_slug }}

about:
  home: https://github.com/pennmem/{{ cookiecutter.project_slug }}
  # license: FIXME
  # license_file: FIXME
